stages:
  - stage: 'BUILD_DEPLOY_ECHO'
    displayName: Plan & Apply Bootstrap
    dependsOn:
    variables:
      priority: 100
    jobs:
      - job: echo_hello_world
        displayName: echo job
        steps:
          - script: |
              echo "hello world"
            displayName: $(region_name) - echo step
          - checkout: self
            fetchDepth: 1
      - job: manual_approval
        dependsOn: echo_hello_world
        displayName: Manual Approval
        pool: server
        timeoutInMinutes: 4320 # job times out in 3 days
        steps:
          - task: ManualValidation@0
            displayName: 'Manual Approval'
            timeoutInMinutes: 1440 # task times out in 1 day
            inputs:
              notifyUsers: |
                manoj7shekhawat@gmail.com
              instructions: 'Please verify the build plan and resume'
              onTimeout: 'reject'
      - job: echo_done
        displayName:  Other echo job
        dependsOn:
          - manual_approval
          - echo_hello_world
        steps:
          - script: |
              echo "DONE"
            displayName: ${{ variables.region_name }} - yet another echo step